# Generated by Django 5.2.8 on 2025-12-04 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('algoML', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historique',
            name='confidence',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
